// <auto-generated />
using System;
using CSharpTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241007144224_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CSharpTest.Models.Guest", b =>
                {
                    b.Property<int>("Guest_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("guest_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Guest_id"));

                    b.Property<DateOnly>("Guest_birthdate")
                        .HasColumnType("date")
                        .HasColumnName("guest_birthdate");

                    b.Property<string>("Guest_email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("guest_email");

                    b.Property<string>("Guest_first_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("guest_first_name");

                    b.Property<string>("Guest_identification_number")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("guest_identification_number");

                    b.Property<string>("Guest_last_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("guest_last_name");

                    b.Property<string>("Guest_phone_number")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("guest_phone_number");

                    b.HasKey("Guest_id");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Guest_id = 1,
                            Guest_birthdate = new DateOnly(2022, 6, 10),
                            Guest_email = "Natasha.Heller@hotmail.com",
                            Guest_first_name = "Sasha",
                            Guest_identification_number = "9886792480",
                            Guest_last_name = "Dickinson",
                            Guest_phone_number = "2484762545"
                        },
                        new
                        {
                            Guest_id = 2,
                            Guest_birthdate = new DateOnly(2016, 1, 5),
                            Guest_email = "Coty.Hahn98@yahoo.com",
                            Guest_first_name = "Elody",
                            Guest_identification_number = "9963703119",
                            Guest_last_name = "Kutch",
                            Guest_phone_number = "6528289449"
                        },
                        new
                        {
                            Guest_id = 3,
                            Guest_birthdate = new DateOnly(2017, 11, 13),
                            Guest_email = "Rickey.Schimmel91@gmail.com",
                            Guest_first_name = "Skylar",
                            Guest_identification_number = "6826338740",
                            Guest_last_name = "Smith",
                            Guest_phone_number = "4004423123"
                        },
                        new
                        {
                            Guest_id = 4,
                            Guest_birthdate = new DateOnly(1995, 10, 15),
                            Guest_email = "Roslyn.Weimann22@gmail.com",
                            Guest_first_name = "Kaleb",
                            Guest_identification_number = "7138018402",
                            Guest_last_name = "Satterfield",
                            Guest_phone_number = "9769942468"
                        },
                        new
                        {
                            Guest_id = 5,
                            Guest_birthdate = new DateOnly(2010, 5, 23),
                            Guest_email = "Tanner.Kris@yahoo.com",
                            Guest_first_name = "Jamarcus",
                            Guest_identification_number = "5777516868",
                            Guest_last_name = "Doyle",
                            Guest_phone_number = "5186212234"
                        },
                        new
                        {
                            Guest_id = 6,
                            Guest_birthdate = new DateOnly(2010, 10, 30),
                            Guest_email = "Anne.Cummerata17@gmail.com",
                            Guest_first_name = "Savion",
                            Guest_identification_number = "3891558710",
                            Guest_last_name = "Fritsch",
                            Guest_phone_number = "3427681243"
                        },
                        new
                        {
                            Guest_id = 7,
                            Guest_birthdate = new DateOnly(2013, 9, 7),
                            Guest_email = "Timmy.Reilly@hotmail.com",
                            Guest_first_name = "Estell",
                            Guest_identification_number = "4844624982",
                            Guest_last_name = "Klocko",
                            Guest_phone_number = "1495944025"
                        },
                        new
                        {
                            Guest_id = 8,
                            Guest_birthdate = new DateOnly(2008, 6, 7),
                            Guest_email = "Princess.Barton@gmail.com",
                            Guest_first_name = "Leanne",
                            Guest_identification_number = "8706775740",
                            Guest_last_name = "Douglas",
                            Guest_phone_number = "2165841246"
                        },
                        new
                        {
                            Guest_id = 9,
                            Guest_birthdate = new DateOnly(2023, 12, 21),
                            Guest_email = "Sophia_Sporer@gmail.com",
                            Guest_first_name = "Mariah",
                            Guest_identification_number = "7594014750",
                            Guest_last_name = "Lynch",
                            Guest_phone_number = "4033062872"
                        },
                        new
                        {
                            Guest_id = 10,
                            Guest_birthdate = new DateOnly(2017, 6, 16),
                            Guest_email = "Leif_Kerluke99@hotmail.com",
                            Guest_first_name = "Chaya",
                            Guest_identification_number = "8684543060",
                            Guest_last_name = "Borer",
                            Guest_phone_number = "3754958379"
                        },
                        new
                        {
                            Guest_id = 11,
                            Guest_birthdate = new DateOnly(2004, 8, 6),
                            Guest_email = "Aryanna_Kiehn@gmail.com",
                            Guest_first_name = "Muriel",
                            Guest_identification_number = "7827113990",
                            Guest_last_name = "Connelly",
                            Guest_phone_number = "1380480019"
                        },
                        new
                        {
                            Guest_id = 12,
                            Guest_birthdate = new DateOnly(1995, 9, 13),
                            Guest_email = "Sammy.Abshire@gmail.com",
                            Guest_first_name = "Tad",
                            Guest_identification_number = "4388710218",
                            Guest_last_name = "Lockman",
                            Guest_phone_number = "6145656851"
                        },
                        new
                        {
                            Guest_id = 13,
                            Guest_birthdate = new DateOnly(1995, 10, 11),
                            Guest_email = "Ressie_Moore25@yahoo.com",
                            Guest_first_name = "Ronaldo",
                            Guest_identification_number = "3163558966",
                            Guest_last_name = "Kemmer",
                            Guest_phone_number = "2563416817"
                        },
                        new
                        {
                            Guest_id = 14,
                            Guest_birthdate = new DateOnly(2017, 8, 8),
                            Guest_email = "Ronny_Upton62@gmail.com",
                            Guest_first_name = "Macie",
                            Guest_identification_number = "8981289482",
                            Guest_last_name = "Douglas",
                            Guest_phone_number = "4114717539"
                        },
                        new
                        {
                            Guest_id = 15,
                            Guest_birthdate = new DateOnly(2016, 11, 22),
                            Guest_email = "Faye.Legros79@gmail.com",
                            Guest_first_name = "Julius",
                            Guest_identification_number = "7180084656",
                            Guest_last_name = "Mitchell",
                            Guest_phone_number = "8757141655"
                        },
                        new
                        {
                            Guest_id = 16,
                            Guest_birthdate = new DateOnly(2020, 7, 3),
                            Guest_email = "Margarita39@gmail.com",
                            Guest_first_name = "Dino",
                            Guest_identification_number = "1457778082",
                            Guest_last_name = "Grimes",
                            Guest_phone_number = "1474800200"
                        },
                        new
                        {
                            Guest_id = 17,
                            Guest_birthdate = new DateOnly(2010, 12, 4),
                            Guest_email = "Frankie.Barrows@gmail.com",
                            Guest_first_name = "Caleigh",
                            Guest_identification_number = "9777923458",
                            Guest_last_name = "Johns",
                            Guest_phone_number = "6827602889"
                        },
                        new
                        {
                            Guest_id = 18,
                            Guest_birthdate = new DateOnly(2011, 1, 1),
                            Guest_email = "Simeon_Trantow@hotmail.com",
                            Guest_first_name = "Dean",
                            Guest_identification_number = "3127649883",
                            Guest_last_name = "Funk",
                            Guest_phone_number = "7240065680"
                        },
                        new
                        {
                            Guest_id = 19,
                            Guest_birthdate = new DateOnly(2017, 6, 27),
                            Guest_email = "Haylie_Greenfelder@hotmail.com",
                            Guest_first_name = "Fabiola",
                            Guest_identification_number = "2616491007",
                            Guest_last_name = "Flatley",
                            Guest_phone_number = "7470881755"
                        },
                        new
                        {
                            Guest_id = 20,
                            Guest_birthdate = new DateOnly(2010, 7, 9),
                            Guest_email = "Aliyah.Schiller@yahoo.com",
                            Guest_first_name = "Marc",
                            Guest_identification_number = "1981956192",
                            Guest_last_name = "Schinner",
                            Guest_phone_number = "9557395578"
                        },
                        new
                        {
                            Guest_id = 21,
                            Guest_birthdate = new DateOnly(2013, 8, 5),
                            Guest_email = "Durward_Greenfelder50@hotmail.com",
                            Guest_first_name = "Geovanni",
                            Guest_identification_number = "3574581133",
                            Guest_last_name = "DuBuque",
                            Guest_phone_number = "4099885120"
                        },
                        new
                        {
                            Guest_id = 22,
                            Guest_birthdate = new DateOnly(2016, 10, 25),
                            Guest_email = "Betty.Pfannerstill@yahoo.com",
                            Guest_first_name = "Guido",
                            Guest_identification_number = "4232499679",
                            Guest_last_name = "Ruecker",
                            Guest_phone_number = "1012409732"
                        },
                        new
                        {
                            Guest_id = 23,
                            Guest_birthdate = new DateOnly(2005, 7, 22),
                            Guest_email = "Edison_Schmeler@hotmail.com",
                            Guest_first_name = "Geraldine",
                            Guest_identification_number = "3572707050",
                            Guest_last_name = "Hauck",
                            Guest_phone_number = "9092530691"
                        },
                        new
                        {
                            Guest_id = 24,
                            Guest_birthdate = new DateOnly(2021, 9, 6),
                            Guest_email = "Shanon60@hotmail.com",
                            Guest_first_name = "Quinn",
                            Guest_identification_number = "5743343262",
                            Guest_last_name = "Von",
                            Guest_phone_number = "6637328004"
                        },
                        new
                        {
                            Guest_id = 25,
                            Guest_birthdate = new DateOnly(2006, 4, 21),
                            Guest_email = "Onie_Carter@gmail.com",
                            Guest_first_name = "Pablo",
                            Guest_identification_number = "8162114314",
                            Guest_last_name = "Lind",
                            Guest_phone_number = "6759892571"
                        },
                        new
                        {
                            Guest_id = 26,
                            Guest_birthdate = new DateOnly(2017, 3, 22),
                            Guest_email = "River.Hammes96@hotmail.com",
                            Guest_first_name = "Jude",
                            Guest_identification_number = "8635083384",
                            Guest_last_name = "Hickle",
                            Guest_phone_number = "8141363074"
                        },
                        new
                        {
                            Guest_id = 27,
                            Guest_birthdate = new DateOnly(2011, 3, 25),
                            Guest_email = "Kenya7@yahoo.com",
                            Guest_first_name = "Jennie",
                            Guest_identification_number = "2386405993",
                            Guest_last_name = "Stroman",
                            Guest_phone_number = "6438703935"
                        },
                        new
                        {
                            Guest_id = 28,
                            Guest_birthdate = new DateOnly(2019, 1, 7),
                            Guest_email = "Shanna.Hackett68@hotmail.com",
                            Guest_first_name = "Lauren",
                            Guest_identification_number = "4883438036",
                            Guest_last_name = "Gislason",
                            Guest_phone_number = "6104634480"
                        },
                        new
                        {
                            Guest_id = 29,
                            Guest_birthdate = new DateOnly(2002, 1, 18),
                            Guest_email = "Milan2@yahoo.com",
                            Guest_first_name = "Gaston",
                            Guest_identification_number = "5373210384",
                            Guest_last_name = "Dickens",
                            Guest_phone_number = "7797802836"
                        },
                        new
                        {
                            Guest_id = 30,
                            Guest_birthdate = new DateOnly(2005, 3, 6),
                            Guest_email = "Deion.Berge92@yahoo.com",
                            Guest_first_name = "Darion",
                            Guest_identification_number = "6637233503",
                            Guest_last_name = "Feeney",
                            Guest_phone_number = "2749638301"
                        },
                        new
                        {
                            Guest_id = 31,
                            Guest_birthdate = new DateOnly(2000, 9, 23),
                            Guest_email = "Josue2@gmail.com",
                            Guest_first_name = "Mustafa",
                            Guest_identification_number = "6536068612",
                            Guest_last_name = "McKenzie",
                            Guest_phone_number = "7941236558"
                        },
                        new
                        {
                            Guest_id = 32,
                            Guest_birthdate = new DateOnly(2018, 10, 29),
                            Guest_email = "Maximilian60@hotmail.com",
                            Guest_first_name = "Keshaun",
                            Guest_identification_number = "7885118563",
                            Guest_last_name = "McGlynn",
                            Guest_phone_number = "7425796707"
                        },
                        new
                        {
                            Guest_id = 33,
                            Guest_birthdate = new DateOnly(2018, 1, 10),
                            Guest_email = "Destiny.Boehm39@hotmail.com",
                            Guest_first_name = "Tom",
                            Guest_identification_number = "7328135185",
                            Guest_last_name = "Buckridge",
                            Guest_phone_number = "2433805278"
                        },
                        new
                        {
                            Guest_id = 34,
                            Guest_birthdate = new DateOnly(2020, 8, 1),
                            Guest_email = "Valentina46@yahoo.com",
                            Guest_first_name = "Louisa",
                            Guest_identification_number = "4467522998",
                            Guest_last_name = "Batz",
                            Guest_phone_number = "3884127528"
                        },
                        new
                        {
                            Guest_id = 35,
                            Guest_birthdate = new DateOnly(2010, 4, 20),
                            Guest_email = "Crystal_Leannon@gmail.com",
                            Guest_first_name = "Colleen",
                            Guest_identification_number = "5402567079",
                            Guest_last_name = "Auer",
                            Guest_phone_number = "2597196221"
                        },
                        new
                        {
                            Guest_id = 36,
                            Guest_birthdate = new DateOnly(2012, 11, 26),
                            Guest_email = "Sylvan22@gmail.com",
                            Guest_first_name = "Ed",
                            Guest_identification_number = "6454410194",
                            Guest_last_name = "Dicki",
                            Guest_phone_number = "4929594802"
                        },
                        new
                        {
                            Guest_id = 37,
                            Guest_birthdate = new DateOnly(2002, 9, 11),
                            Guest_email = "Terrance_Kris@hotmail.com",
                            Guest_first_name = "Emiliano",
                            Guest_identification_number = "5939523552",
                            Guest_last_name = "Langosh",
                            Guest_phone_number = "8274482408"
                        },
                        new
                        {
                            Guest_id = 38,
                            Guest_birthdate = new DateOnly(2021, 10, 22),
                            Guest_email = "Gay.Erdman91@hotmail.com",
                            Guest_first_name = "Uriah",
                            Guest_identification_number = "6782127859",
                            Guest_last_name = "Gottlieb",
                            Guest_phone_number = "6533202070"
                        },
                        new
                        {
                            Guest_id = 39,
                            Guest_birthdate = new DateOnly(2000, 5, 24),
                            Guest_email = "Vivienne68@gmail.com",
                            Guest_first_name = "Houston",
                            Guest_identification_number = "2890195708",
                            Guest_last_name = "Lubowitz",
                            Guest_phone_number = "8863455836"
                        },
                        new
                        {
                            Guest_id = 40,
                            Guest_birthdate = new DateOnly(2017, 2, 25),
                            Guest_email = "Bailee_Lebsack@gmail.com",
                            Guest_first_name = "Chet",
                            Guest_identification_number = "3208436837",
                            Guest_last_name = "Treutel",
                            Guest_phone_number = "9835333817"
                        },
                        new
                        {
                            Guest_id = 41,
                            Guest_birthdate = new DateOnly(2015, 11, 29),
                            Guest_email = "Nikki31@yahoo.com",
                            Guest_first_name = "Dina",
                            Guest_identification_number = "2814692367",
                            Guest_last_name = "Bauch",
                            Guest_phone_number = "9898439740"
                        },
                        new
                        {
                            Guest_id = 42,
                            Guest_birthdate = new DateOnly(1997, 2, 27),
                            Guest_email = "Lindsey89@hotmail.com",
                            Guest_first_name = "Daphney",
                            Guest_identification_number = "3932973651",
                            Guest_last_name = "Schneider",
                            Guest_phone_number = "7054607465"
                        },
                        new
                        {
                            Guest_id = 43,
                            Guest_birthdate = new DateOnly(2010, 8, 20),
                            Guest_email = "Liza.Langworth90@hotmail.com",
                            Guest_first_name = "Sabrina",
                            Guest_identification_number = "2139744424",
                            Guest_last_name = "Rohan",
                            Guest_phone_number = "3907445223"
                        },
                        new
                        {
                            Guest_id = 44,
                            Guest_birthdate = new DateOnly(2010, 12, 13),
                            Guest_email = "Krystel77@hotmail.com",
                            Guest_first_name = "Araceli",
                            Guest_identification_number = "6920190587",
                            Guest_last_name = "Powlowski",
                            Guest_phone_number = "2959705789"
                        },
                        new
                        {
                            Guest_id = 45,
                            Guest_birthdate = new DateOnly(2011, 8, 12),
                            Guest_email = "Demetrius.Hermann@yahoo.com",
                            Guest_first_name = "Lamar",
                            Guest_identification_number = "2155673289",
                            Guest_last_name = "Ward",
                            Guest_phone_number = "1112196079"
                        },
                        new
                        {
                            Guest_id = 46,
                            Guest_birthdate = new DateOnly(2015, 5, 15),
                            Guest_email = "Nelle79@hotmail.com",
                            Guest_first_name = "Jazmyne",
                            Guest_identification_number = "8876013231",
                            Guest_last_name = "Mann",
                            Guest_phone_number = "3930165233"
                        },
                        new
                        {
                            Guest_id = 47,
                            Guest_birthdate = new DateOnly(2005, 5, 2),
                            Guest_email = "Percival_Beer@hotmail.com",
                            Guest_first_name = "Shawna",
                            Guest_identification_number = "9876613818",
                            Guest_last_name = "Mills",
                            Guest_phone_number = "7681914532"
                        },
                        new
                        {
                            Guest_id = 48,
                            Guest_birthdate = new DateOnly(2005, 2, 13),
                            Guest_email = "Sasha93@yahoo.com",
                            Guest_first_name = "Kenton",
                            Guest_identification_number = "4720285537",
                            Guest_last_name = "Wunsch",
                            Guest_phone_number = "4656966195"
                        },
                        new
                        {
                            Guest_id = 49,
                            Guest_birthdate = new DateOnly(2008, 7, 15),
                            Guest_email = "Ervin45@hotmail.com",
                            Guest_first_name = "Agustina",
                            Guest_identification_number = "6052648727",
                            Guest_last_name = "Kemmer",
                            Guest_phone_number = "1419939469"
                        },
                        new
                        {
                            Guest_id = 50,
                            Guest_birthdate = new DateOnly(1996, 5, 17),
                            Guest_email = "Javon3@hotmail.com",
                            Guest_first_name = "Nelle",
                            Guest_identification_number = "7145222184",
                            Guest_last_name = "Dickens",
                            Guest_phone_number = "6808350313"
                        },
                        new
                        {
                            Guest_id = 51,
                            Guest_birthdate = new DateOnly(1994, 11, 17),
                            Guest_email = "Graciela5@yahoo.com",
                            Guest_first_name = "Chauncey",
                            Guest_identification_number = "2006997125",
                            Guest_last_name = "Nicolas",
                            Guest_phone_number = "5857827971"
                        },
                        new
                        {
                            Guest_id = 52,
                            Guest_birthdate = new DateOnly(2003, 6, 14),
                            Guest_email = "Maximus92@gmail.com",
                            Guest_first_name = "Freda",
                            Guest_identification_number = "3842601552",
                            Guest_last_name = "Morissette",
                            Guest_phone_number = "8613061063"
                        },
                        new
                        {
                            Guest_id = 53,
                            Guest_birthdate = new DateOnly(2001, 7, 21),
                            Guest_email = "Martin.Von84@yahoo.com",
                            Guest_first_name = "Parker",
                            Guest_identification_number = "7012759950",
                            Guest_last_name = "Harber",
                            Guest_phone_number = "6420772947"
                        },
                        new
                        {
                            Guest_id = 54,
                            Guest_birthdate = new DateOnly(2002, 11, 25),
                            Guest_email = "Nicolas78@hotmail.com",
                            Guest_first_name = "Rosendo",
                            Guest_identification_number = "7439331064",
                            Guest_last_name = "Wiza",
                            Guest_phone_number = "6621265495"
                        },
                        new
                        {
                            Guest_id = 55,
                            Guest_birthdate = new DateOnly(2008, 5, 8),
                            Guest_email = "Cecil_Stanton@gmail.com",
                            Guest_first_name = "Hiram",
                            Guest_identification_number = "5408247266",
                            Guest_last_name = "Kutch",
                            Guest_phone_number = "3860132138"
                        },
                        new
                        {
                            Guest_id = 56,
                            Guest_birthdate = new DateOnly(1997, 12, 23),
                            Guest_email = "Sylvester_Murphy@gmail.com",
                            Guest_first_name = "Major",
                            Guest_identification_number = "3068005428",
                            Guest_last_name = "Fisher",
                            Guest_phone_number = "9284975993"
                        },
                        new
                        {
                            Guest_id = 57,
                            Guest_birthdate = new DateOnly(2023, 1, 8),
                            Guest_email = "Sophie.Satterfield36@hotmail.com",
                            Guest_first_name = "Alanis",
                            Guest_identification_number = "5806225526",
                            Guest_last_name = "West",
                            Guest_phone_number = "8709956630"
                        },
                        new
                        {
                            Guest_id = 58,
                            Guest_birthdate = new DateOnly(1995, 6, 6),
                            Guest_email = "Gardner95@gmail.com",
                            Guest_first_name = "Marcellus",
                            Guest_identification_number = "7666101622",
                            Guest_last_name = "Conroy",
                            Guest_phone_number = "1586388092"
                        },
                        new
                        {
                            Guest_id = 59,
                            Guest_birthdate = new DateOnly(2004, 5, 25),
                            Guest_email = "Verna.Boyer@hotmail.com",
                            Guest_first_name = "Eldridge",
                            Guest_identification_number = "7851231738",
                            Guest_last_name = "Greenfelder",
                            Guest_phone_number = "8081306455"
                        },
                        new
                        {
                            Guest_id = 60,
                            Guest_birthdate = new DateOnly(2003, 11, 28),
                            Guest_email = "Oma86@yahoo.com",
                            Guest_first_name = "Joan",
                            Guest_identification_number = "4650256663",
                            Guest_last_name = "Wilderman",
                            Guest_phone_number = "7400087453"
                        },
                        new
                        {
                            Guest_id = 61,
                            Guest_birthdate = new DateOnly(2002, 8, 3),
                            Guest_email = "Kailyn_Denesik26@hotmail.com",
                            Guest_first_name = "Shaina",
                            Guest_identification_number = "7934948731",
                            Guest_last_name = "Robel",
                            Guest_phone_number = "3786255193"
                        },
                        new
                        {
                            Guest_id = 62,
                            Guest_birthdate = new DateOnly(2002, 3, 5),
                            Guest_email = "Edgardo_Blanda@hotmail.com",
                            Guest_first_name = "Ubaldo",
                            Guest_identification_number = "5930113970",
                            Guest_last_name = "Corwin",
                            Guest_phone_number = "5018332496"
                        },
                        new
                        {
                            Guest_id = 63,
                            Guest_birthdate = new DateOnly(2012, 9, 24),
                            Guest_email = "Roger_Wolf72@gmail.com",
                            Guest_first_name = "Colton",
                            Guest_identification_number = "6055570380",
                            Guest_last_name = "Kuhn",
                            Guest_phone_number = "7054346015"
                        },
                        new
                        {
                            Guest_id = 64,
                            Guest_birthdate = new DateOnly(2017, 9, 9),
                            Guest_email = "Scot.Huels@hotmail.com",
                            Guest_first_name = "Eldora",
                            Guest_identification_number = "3759635354",
                            Guest_last_name = "Carroll",
                            Guest_phone_number = "7068376086"
                        },
                        new
                        {
                            Guest_id = 65,
                            Guest_birthdate = new DateOnly(2005, 11, 13),
                            Guest_email = "Magali_Kunde96@yahoo.com",
                            Guest_first_name = "Hershel",
                            Guest_identification_number = "8306812081",
                            Guest_last_name = "Bartoletti",
                            Guest_phone_number = "3714410535"
                        },
                        new
                        {
                            Guest_id = 66,
                            Guest_birthdate = new DateOnly(2024, 6, 25),
                            Guest_email = "Tyra.Kuhn@yahoo.com",
                            Guest_first_name = "Virginie",
                            Guest_identification_number = "3459258152",
                            Guest_last_name = "Hackett",
                            Guest_phone_number = "8476020384"
                        },
                        new
                        {
                            Guest_id = 67,
                            Guest_birthdate = new DateOnly(1995, 5, 21),
                            Guest_email = "Oran73@gmail.com",
                            Guest_first_name = "Maxime",
                            Guest_identification_number = "8075178759",
                            Guest_last_name = "Marks",
                            Guest_phone_number = "7414705616"
                        },
                        new
                        {
                            Guest_id = 68,
                            Guest_birthdate = new DateOnly(1996, 6, 6),
                            Guest_email = "Olaf56@yahoo.com",
                            Guest_first_name = "Kelly",
                            Guest_identification_number = "3122969422",
                            Guest_last_name = "Quitzon",
                            Guest_phone_number = "1030412933"
                        },
                        new
                        {
                            Guest_id = 69,
                            Guest_birthdate = new DateOnly(2005, 2, 2),
                            Guest_email = "Jonas.Heaney@gmail.com",
                            Guest_first_name = "Khalil",
                            Guest_identification_number = "9456901944",
                            Guest_last_name = "Rowe",
                            Guest_phone_number = "7082759429"
                        },
                        new
                        {
                            Guest_id = 70,
                            Guest_birthdate = new DateOnly(2002, 11, 7),
                            Guest_email = "Nelle.Muller@hotmail.com",
                            Guest_first_name = "Idell",
                            Guest_identification_number = "3499416143",
                            Guest_last_name = "Barrows",
                            Guest_phone_number = "2829303712"
                        },
                        new
                        {
                            Guest_id = 71,
                            Guest_birthdate = new DateOnly(2002, 8, 6),
                            Guest_email = "Rod.Homenick@gmail.com",
                            Guest_first_name = "Dante",
                            Guest_identification_number = "3017597000",
                            Guest_last_name = "Harris",
                            Guest_phone_number = "8500954659"
                        },
                        new
                        {
                            Guest_id = 72,
                            Guest_birthdate = new DateOnly(2018, 3, 12),
                            Guest_email = "Mozell_Steuber@yahoo.com",
                            Guest_first_name = "Kacie",
                            Guest_identification_number = "5343282235",
                            Guest_last_name = "Stamm",
                            Guest_phone_number = "1942849086"
                        },
                        new
                        {
                            Guest_id = 73,
                            Guest_birthdate = new DateOnly(2024, 5, 15),
                            Guest_email = "Julianne_Ratke@gmail.com",
                            Guest_first_name = "Hannah",
                            Guest_identification_number = "5387900799",
                            Guest_last_name = "Willms",
                            Guest_phone_number = "8740443226"
                        },
                        new
                        {
                            Guest_id = 74,
                            Guest_birthdate = new DateOnly(2007, 1, 29),
                            Guest_email = "Makenna_Prohaska22@yahoo.com",
                            Guest_first_name = "Crawford",
                            Guest_identification_number = "5276062452",
                            Guest_last_name = "Crooks",
                            Guest_phone_number = "2898281569"
                        },
                        new
                        {
                            Guest_id = 75,
                            Guest_birthdate = new DateOnly(2022, 5, 5),
                            Guest_email = "Rashad_Schroeder61@yahoo.com",
                            Guest_first_name = "Arnaldo",
                            Guest_identification_number = "6227999085",
                            Guest_last_name = "Marvin",
                            Guest_phone_number = "3104173311"
                        },
                        new
                        {
                            Guest_id = 76,
                            Guest_birthdate = new DateOnly(2016, 2, 11),
                            Guest_email = "Leonor.Hackett89@yahoo.com",
                            Guest_first_name = "Scotty",
                            Guest_identification_number = "7871774512",
                            Guest_last_name = "Upton",
                            Guest_phone_number = "9104701389"
                        },
                        new
                        {
                            Guest_id = 77,
                            Guest_birthdate = new DateOnly(2020, 3, 25),
                            Guest_email = "Ettie.Halvorson@hotmail.com",
                            Guest_first_name = "Gail",
                            Guest_identification_number = "6931154109",
                            Guest_last_name = "Casper",
                            Guest_phone_number = "6445124000"
                        },
                        new
                        {
                            Guest_id = 78,
                            Guest_birthdate = new DateOnly(2021, 11, 25),
                            Guest_email = "Zane8@gmail.com",
                            Guest_first_name = "Ezra",
                            Guest_identification_number = "7316047814",
                            Guest_last_name = "Brakus",
                            Guest_phone_number = "8945935603"
                        },
                        new
                        {
                            Guest_id = 79,
                            Guest_birthdate = new DateOnly(2006, 12, 1),
                            Guest_email = "Nora.Goldner@yahoo.com",
                            Guest_first_name = "Dedrick",
                            Guest_identification_number = "3853141044",
                            Guest_last_name = "Hane",
                            Guest_phone_number = "4608014333"
                        },
                        new
                        {
                            Guest_id = 80,
                            Guest_birthdate = new DateOnly(1996, 6, 15),
                            Guest_email = "Raymond_Wisoky13@gmail.com",
                            Guest_first_name = "Madilyn",
                            Guest_identification_number = "2346664211",
                            Guest_last_name = "Baumbach",
                            Guest_phone_number = "8699526166"
                        },
                        new
                        {
                            Guest_id = 81,
                            Guest_birthdate = new DateOnly(2010, 12, 6),
                            Guest_email = "Marion.Zboncak98@gmail.com",
                            Guest_first_name = "Britney",
                            Guest_identification_number = "2524060286",
                            Guest_last_name = "Homenick",
                            Guest_phone_number = "1212804189"
                        },
                        new
                        {
                            Guest_id = 82,
                            Guest_birthdate = new DateOnly(2022, 11, 2),
                            Guest_email = "Alysa_Ebert@hotmail.com",
                            Guest_first_name = "Gayle",
                            Guest_identification_number = "5920200364",
                            Guest_last_name = "Hegmann",
                            Guest_phone_number = "5842122255"
                        },
                        new
                        {
                            Guest_id = 83,
                            Guest_birthdate = new DateOnly(2018, 5, 7),
                            Guest_email = "Liana_Hermiston74@gmail.com",
                            Guest_first_name = "Jayson",
                            Guest_identification_number = "9841471850",
                            Guest_last_name = "Ryan",
                            Guest_phone_number = "6029885790"
                        },
                        new
                        {
                            Guest_id = 84,
                            Guest_birthdate = new DateOnly(2019, 7, 6),
                            Guest_email = "Cale72@yahoo.com",
                            Guest_first_name = "Antonietta",
                            Guest_identification_number = "5227374197",
                            Guest_last_name = "Cummings",
                            Guest_phone_number = "2880714304"
                        },
                        new
                        {
                            Guest_id = 85,
                            Guest_birthdate = new DateOnly(2021, 2, 3),
                            Guest_email = "Nichole.Johnston@gmail.com",
                            Guest_first_name = "Jayce",
                            Guest_identification_number = "7821227857",
                            Guest_last_name = "Jerde",
                            Guest_phone_number = "7636126569"
                        },
                        new
                        {
                            Guest_id = 86,
                            Guest_birthdate = new DateOnly(2009, 10, 30),
                            Guest_email = "Ralph_Bednar88@hotmail.com",
                            Guest_first_name = "Cornell",
                            Guest_identification_number = "4495914120",
                            Guest_last_name = "Erdman",
                            Guest_phone_number = "8361235188"
                        },
                        new
                        {
                            Guest_id = 87,
                            Guest_birthdate = new DateOnly(2006, 9, 26),
                            Guest_email = "Dion.Auer@yahoo.com",
                            Guest_first_name = "Alexzander",
                            Guest_identification_number = "6165746059",
                            Guest_last_name = "Bartell",
                            Guest_phone_number = "9371513400"
                        },
                        new
                        {
                            Guest_id = 88,
                            Guest_birthdate = new DateOnly(2011, 9, 27),
                            Guest_email = "Avery46@yahoo.com",
                            Guest_first_name = "Lorenz",
                            Guest_identification_number = "9821994423",
                            Guest_last_name = "Armstrong",
                            Guest_phone_number = "1429796443"
                        },
                        new
                        {
                            Guest_id = 89,
                            Guest_birthdate = new DateOnly(2016, 3, 24),
                            Guest_email = "Annette.Runte@gmail.com",
                            Guest_first_name = "Stan",
                            Guest_identification_number = "3344877272",
                            Guest_last_name = "Kohler",
                            Guest_phone_number = "5195034873"
                        },
                        new
                        {
                            Guest_id = 90,
                            Guest_birthdate = new DateOnly(1995, 1, 17),
                            Guest_email = "Marilyne29@gmail.com",
                            Guest_first_name = "Elise",
                            Guest_identification_number = "7583194533",
                            Guest_last_name = "Champlin",
                            Guest_phone_number = "8184108100"
                        },
                        new
                        {
                            Guest_id = 91,
                            Guest_birthdate = new DateOnly(2015, 8, 23),
                            Guest_email = "Chanelle37@yahoo.com",
                            Guest_first_name = "Jennings",
                            Guest_identification_number = "7856869217",
                            Guest_last_name = "Kovacek",
                            Guest_phone_number = "9907223273"
                        },
                        new
                        {
                            Guest_id = 92,
                            Guest_birthdate = new DateOnly(1998, 5, 13),
                            Guest_email = "Harry_Torphy@hotmail.com",
                            Guest_first_name = "Thora",
                            Guest_identification_number = "5508450791",
                            Guest_last_name = "Kuhlman",
                            Guest_phone_number = "7337409817"
                        },
                        new
                        {
                            Guest_id = 93,
                            Guest_birthdate = new DateOnly(2005, 11, 30),
                            Guest_email = "Allie.King0@yahoo.com",
                            Guest_first_name = "Norval",
                            Guest_identification_number = "2769212804",
                            Guest_last_name = "Kihn",
                            Guest_phone_number = "9449545489"
                        },
                        new
                        {
                            Guest_id = 94,
                            Guest_birthdate = new DateOnly(2011, 11, 13),
                            Guest_email = "Blake_Ankunding23@gmail.com",
                            Guest_first_name = "Sid",
                            Guest_identification_number = "4416103223",
                            Guest_last_name = "Carter",
                            Guest_phone_number = "9705170626"
                        },
                        new
                        {
                            Guest_id = 95,
                            Guest_birthdate = new DateOnly(2005, 8, 14),
                            Guest_email = "Kian.Weber71@yahoo.com",
                            Guest_first_name = "Reyes",
                            Guest_identification_number = "5227729998",
                            Guest_last_name = "Lehner",
                            Guest_phone_number = "1513865335"
                        },
                        new
                        {
                            Guest_id = 96,
                            Guest_birthdate = new DateOnly(2016, 1, 31),
                            Guest_email = "Vicenta.Schaden@yahoo.com",
                            Guest_first_name = "Morris",
                            Guest_identification_number = "2358347408",
                            Guest_last_name = "Corkery",
                            Guest_phone_number = "2674568372"
                        },
                        new
                        {
                            Guest_id = 97,
                            Guest_birthdate = new DateOnly(1996, 1, 5),
                            Guest_email = "Montana.Sauer90@yahoo.com",
                            Guest_first_name = "Kelvin",
                            Guest_identification_number = "8485502451",
                            Guest_last_name = "Von",
                            Guest_phone_number = "6721389730"
                        },
                        new
                        {
                            Guest_id = 98,
                            Guest_birthdate = new DateOnly(2019, 1, 11),
                            Guest_email = "Seth.Volkman@gmail.com",
                            Guest_first_name = "Gregoria",
                            Guest_identification_number = "3875135937",
                            Guest_last_name = "Sporer",
                            Guest_phone_number = "5026738793"
                        },
                        new
                        {
                            Guest_id = 99,
                            Guest_birthdate = new DateOnly(2006, 4, 14),
                            Guest_email = "Barton90@hotmail.com",
                            Guest_first_name = "Virgie",
                            Guest_identification_number = "5746250449",
                            Guest_last_name = "Becker",
                            Guest_phone_number = "1480694924"
                        },
                        new
                        {
                            Guest_id = 100,
                            Guest_birthdate = new DateOnly(2004, 3, 28),
                            Guest_email = "Ulises_Mann28@yahoo.com",
                            Guest_first_name = "Adelia",
                            Guest_identification_number = "4356958539",
                            Guest_last_name = "Bernhard",
                            Guest_phone_number = "2474094435"
                        });
                });

            modelBuilder.Entity("CSharpTest.Models.Room", b =>
                {
                    b.Property<int>("Room_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Room_id"));

                    b.Property<bool>("Room_availability")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("room_availability");

                    b.Property<int>("Room_max_occupancy_people")
                        .HasColumnType("int")
                        .HasColumnName("room_max_occupancy_people");

                    b.Property<string>("Room_number")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("room_number");

                    b.Property<double>("Room_price_per_night")
                        .HasColumnType("double")
                        .HasColumnName("room_price_per_night");

                    b.Property<int>("Room_type_id")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.HasKey("Room_id");

                    b.HasIndex("Room_type_id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Room_id = 1,
                            Room_availability = true,
                            Room_max_occupancy_people = 74,
                            Room_number = "97",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 2,
                            Room_availability = false,
                            Room_max_occupancy_people = 57,
                            Room_number = "29",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 3,
                            Room_availability = true,
                            Room_max_occupancy_people = 175,
                            Room_number = "97",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 4,
                            Room_availability = false,
                            Room_max_occupancy_people = 187,
                            Room_number = "43",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 5,
                            Room_availability = true,
                            Room_max_occupancy_people = 149,
                            Room_number = "94",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 6,
                            Room_availability = true,
                            Room_max_occupancy_people = 10,
                            Room_number = "6",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 7,
                            Room_availability = true,
                            Room_max_occupancy_people = 172,
                            Room_number = "53",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 8,
                            Room_availability = false,
                            Room_max_occupancy_people = 62,
                            Room_number = "89",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 9,
                            Room_availability = false,
                            Room_max_occupancy_people = 213,
                            Room_number = "72",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 10,
                            Room_availability = true,
                            Room_max_occupancy_people = 25,
                            Room_number = "94",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 11,
                            Room_availability = false,
                            Room_max_occupancy_people = 22,
                            Room_number = "26",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 12,
                            Room_availability = false,
                            Room_max_occupancy_people = 246,
                            Room_number = "57",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 13,
                            Room_availability = true,
                            Room_max_occupancy_people = 168,
                            Room_number = "62",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 14,
                            Room_availability = false,
                            Room_max_occupancy_people = 255,
                            Room_number = "70",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 15,
                            Room_availability = false,
                            Room_max_occupancy_people = 207,
                            Room_number = "76",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 16,
                            Room_availability = true,
                            Room_max_occupancy_people = 229,
                            Room_number = "65",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 17,
                            Room_availability = true,
                            Room_max_occupancy_people = 203,
                            Room_number = "63",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 18,
                            Room_availability = false,
                            Room_max_occupancy_people = 94,
                            Room_number = "59",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 19,
                            Room_availability = false,
                            Room_max_occupancy_people = 170,
                            Room_number = "2",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 20,
                            Room_availability = true,
                            Room_max_occupancy_people = 27,
                            Room_number = "26",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 21,
                            Room_availability = false,
                            Room_max_occupancy_people = 216,
                            Room_number = "26",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 22,
                            Room_availability = false,
                            Room_max_occupancy_people = 89,
                            Room_number = "77",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 23,
                            Room_availability = false,
                            Room_max_occupancy_people = 129,
                            Room_number = "74",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 24,
                            Room_availability = true,
                            Room_max_occupancy_people = 70,
                            Room_number = "37",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 25,
                            Room_availability = true,
                            Room_max_occupancy_people = 74,
                            Room_number = "72",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 26,
                            Room_availability = true,
                            Room_max_occupancy_people = 158,
                            Room_number = "12",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 27,
                            Room_availability = true,
                            Room_max_occupancy_people = 49,
                            Room_number = "31",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 28,
                            Room_availability = false,
                            Room_max_occupancy_people = 215,
                            Room_number = "44",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 29,
                            Room_availability = true,
                            Room_max_occupancy_people = 64,
                            Room_number = "51",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 30,
                            Room_availability = true,
                            Room_max_occupancy_people = 84,
                            Room_number = "3",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 31,
                            Room_availability = false,
                            Room_max_occupancy_people = 150,
                            Room_number = "69",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 32,
                            Room_availability = true,
                            Room_max_occupancy_people = 117,
                            Room_number = "44",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 33,
                            Room_availability = false,
                            Room_max_occupancy_people = 133,
                            Room_number = "89",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 34,
                            Room_availability = true,
                            Room_max_occupancy_people = 179,
                            Room_number = "73",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 35,
                            Room_availability = false,
                            Room_max_occupancy_people = 243,
                            Room_number = "12",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 36,
                            Room_availability = true,
                            Room_max_occupancy_people = 168,
                            Room_number = "31",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 37,
                            Room_availability = false,
                            Room_max_occupancy_people = 130,
                            Room_number = "25",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 38,
                            Room_availability = true,
                            Room_max_occupancy_people = 1,
                            Room_number = "100",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 39,
                            Room_availability = true,
                            Room_max_occupancy_people = 233,
                            Room_number = "68",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 40,
                            Room_availability = false,
                            Room_max_occupancy_people = 168,
                            Room_number = "3",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 41,
                            Room_availability = false,
                            Room_max_occupancy_people = 233,
                            Room_number = "70",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 42,
                            Room_availability = false,
                            Room_max_occupancy_people = 109,
                            Room_number = "21",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 43,
                            Room_availability = false,
                            Room_max_occupancy_people = 212,
                            Room_number = "17",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 44,
                            Room_availability = true,
                            Room_max_occupancy_people = 79,
                            Room_number = "58",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 45,
                            Room_availability = true,
                            Room_max_occupancy_people = 86,
                            Room_number = "51",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 46,
                            Room_availability = true,
                            Room_max_occupancy_people = 28,
                            Room_number = "46",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 47,
                            Room_availability = true,
                            Room_max_occupancy_people = 191,
                            Room_number = "7",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 48,
                            Room_availability = false,
                            Room_max_occupancy_people = 28,
                            Room_number = "59",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 49,
                            Room_availability = false,
                            Room_max_occupancy_people = 51,
                            Room_number = "6",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 50,
                            Room_availability = false,
                            Room_max_occupancy_people = 238,
                            Room_number = "32",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 51,
                            Room_availability = true,
                            Room_max_occupancy_people = 75,
                            Room_number = "17",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 52,
                            Room_availability = true,
                            Room_max_occupancy_people = 195,
                            Room_number = "68",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 53,
                            Room_availability = true,
                            Room_max_occupancy_people = 81,
                            Room_number = "46",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 54,
                            Room_availability = false,
                            Room_max_occupancy_people = 193,
                            Room_number = "7",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 55,
                            Room_availability = false,
                            Room_max_occupancy_people = 218,
                            Room_number = "85",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 56,
                            Room_availability = true,
                            Room_max_occupancy_people = 169,
                            Room_number = "68",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 57,
                            Room_availability = true,
                            Room_max_occupancy_people = 201,
                            Room_number = "78",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 58,
                            Room_availability = false,
                            Room_max_occupancy_people = 211,
                            Room_number = "50",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 59,
                            Room_availability = true,
                            Room_max_occupancy_people = 109,
                            Room_number = "1",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 60,
                            Room_availability = true,
                            Room_max_occupancy_people = 20,
                            Room_number = "34",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 61,
                            Room_availability = false,
                            Room_max_occupancy_people = 86,
                            Room_number = "8",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 62,
                            Room_availability = true,
                            Room_max_occupancy_people = 113,
                            Room_number = "50",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 63,
                            Room_availability = false,
                            Room_max_occupancy_people = 225,
                            Room_number = "28",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 64,
                            Room_availability = true,
                            Room_max_occupancy_people = 88,
                            Room_number = "7",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 65,
                            Room_availability = true,
                            Room_max_occupancy_people = 154,
                            Room_number = "10",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 66,
                            Room_availability = true,
                            Room_max_occupancy_people = 73,
                            Room_number = "14",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 67,
                            Room_availability = false,
                            Room_max_occupancy_people = 184,
                            Room_number = "54",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 68,
                            Room_availability = false,
                            Room_max_occupancy_people = 134,
                            Room_number = "40",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 69,
                            Room_availability = true,
                            Room_max_occupancy_people = 209,
                            Room_number = "32",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 70,
                            Room_availability = false,
                            Room_max_occupancy_people = 254,
                            Room_number = "50",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 71,
                            Room_availability = true,
                            Room_max_occupancy_people = 220,
                            Room_number = "11",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 72,
                            Room_availability = true,
                            Room_max_occupancy_people = 182,
                            Room_number = "14",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 73,
                            Room_availability = false,
                            Room_max_occupancy_people = 95,
                            Room_number = "29",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 74,
                            Room_availability = false,
                            Room_max_occupancy_people = 78,
                            Room_number = "78",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 75,
                            Room_availability = false,
                            Room_max_occupancy_people = 2,
                            Room_number = "29",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 76,
                            Room_availability = true,
                            Room_max_occupancy_people = 161,
                            Room_number = "30",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 77,
                            Room_availability = false,
                            Room_max_occupancy_people = 44,
                            Room_number = "97",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 78,
                            Room_availability = true,
                            Room_max_occupancy_people = 109,
                            Room_number = "76",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 79,
                            Room_availability = true,
                            Room_max_occupancy_people = 208,
                            Room_number = "51",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 80,
                            Room_availability = true,
                            Room_max_occupancy_people = 117,
                            Room_number = "81",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 81,
                            Room_availability = false,
                            Room_max_occupancy_people = 127,
                            Room_number = "11",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 82,
                            Room_availability = true,
                            Room_max_occupancy_people = 20,
                            Room_number = "71",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 83,
                            Room_availability = true,
                            Room_max_occupancy_people = 176,
                            Room_number = "99",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 84,
                            Room_availability = true,
                            Room_max_occupancy_people = 163,
                            Room_number = "62",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 85,
                            Room_availability = true,
                            Room_max_occupancy_people = 237,
                            Room_number = "71",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 86,
                            Room_availability = false,
                            Room_max_occupancy_people = 128,
                            Room_number = "6",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 87,
                            Room_availability = false,
                            Room_max_occupancy_people = 109,
                            Room_number = "3",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 88,
                            Room_availability = false,
                            Room_max_occupancy_people = 253,
                            Room_number = "20",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 89,
                            Room_availability = false,
                            Room_max_occupancy_people = 108,
                            Room_number = "81",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 90,
                            Room_availability = false,
                            Room_max_occupancy_people = 213,
                            Room_number = "35",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 91,
                            Room_availability = false,
                            Room_max_occupancy_people = 58,
                            Room_number = "87",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 92,
                            Room_availability = false,
                            Room_max_occupancy_people = 232,
                            Room_number = "24",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 93,
                            Room_availability = false,
                            Room_max_occupancy_people = 28,
                            Room_number = "45",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 94,
                            Room_availability = true,
                            Room_max_occupancy_people = 196,
                            Room_number = "64",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 95,
                            Room_availability = false,
                            Room_max_occupancy_people = 107,
                            Room_number = "60",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        },
                        new
                        {
                            Room_id = 96,
                            Room_availability = true,
                            Room_max_occupancy_people = 192,
                            Room_number = "67",
                            Room_price_per_night = 150.0,
                            Room_type_id = 3
                        },
                        new
                        {
                            Room_id = 97,
                            Room_availability = false,
                            Room_max_occupancy_people = 20,
                            Room_number = "35",
                            Room_price_per_night = 200.0,
                            Room_type_id = 4
                        },
                        new
                        {
                            Room_id = 98,
                            Room_availability = false,
                            Room_max_occupancy_people = 59,
                            Room_number = "10",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 99,
                            Room_availability = true,
                            Room_max_occupancy_people = 27,
                            Room_number = "34",
                            Room_price_per_night = 80.0,
                            Room_type_id = 2
                        },
                        new
                        {
                            Room_id = 100,
                            Room_availability = true,
                            Room_max_occupancy_people = 191,
                            Room_number = "51",
                            Room_price_per_night = 50.0,
                            Room_type_id = 1
                        });
                });

            modelBuilder.Entity("CSharpTest.Models.Room_type", b =>
                {
                    b.Property<int>("Room_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Room_type_id"));

                    b.Property<string>("Room_type_description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("room_type_description");

                    b.Property<string>("Room_type_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("room_type_name");

                    b.HasKey("Room_type_id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Room_type_id = 1,
                            Room_type_description = "Una acogedora habitación básica con una cama individual, ideal para viajeros solos.",
                            Room_type_name = "Habitación Simple"
                        },
                        new
                        {
                            Room_type_id = 2,
                            Room_type_description = "Ofrece flexibilidad con dos camas individuales o una cama doble, perfecta para parejas o amigos.",
                            Room_type_name = "Habitación Doble"
                        },
                        new
                        {
                            Room_type_id = 3,
                            Room_type_description = "Espaciosa y lujosa, con una cama king size y una sala de estar separada, ideal para quienes buscan confort y exclusividad.",
                            Room_type_name = "Suite"
                        },
                        new
                        {
                            Room_type_id = 4,
                            Room_type_description = "Diseñada para familias, con espacio adicional y varias camas para una estancia cómoda.",
                            Room_type_name = "Habitación Familiar"
                        });
                });

            modelBuilder.Entity("CSharpTest.Models.Room", b =>
                {
                    b.HasOne("CSharpTest.Models.Room_type", "Room_Type")
                        .WithMany()
                        .HasForeignKey("Room_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room_Type");
                });
#pragma warning restore 612, 618
        }
    }
}
